# Project Information
site_name: 'rio-tiler'
site_description: 'Rasterio plugin to read mercator tiles from Cloud Optimized GeoTIFF'

docs_dir: 'docs'
site_dir: 'build'

# Repository
repo_name: 'cogeotiff/rio-tiler'
repo_url: 'https://github.com/cogeotiff/rio-tiler'
edit_uri: 'blob/master/docs/src/'
site_url: 'https://cogeotiff.github.io/rio-tiler/'

# Social links
extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/cogeotiff'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/cogeotiff'
    - icon: 'fontawesome/solid/globe'
      link: 'https://www.cogeo.org/'

# Layout
nav:
  - Home: 'index.md'
  - User Guide:
    - Introduction: 'intro.md'
    - Readers: 'readers.md'
    - Models: 'models.md'
    - Mosaic: 'mosaic.md'
    - Colormaps: 'colormap.md'
  - Advanced Topics:
    - Read Polygon-shaped regions: 'advanced/feature.md'
    - Custom Readers: 'advanced/custom_readers.md'
    - Create a Dynamic Tiler: 'advanced/dynamic_tiler.md'
    - TileMatrixSet: 'advanced/tms.md'
  - Examples:
    - Introduction: 'examples/Using-rio-tiler.ipynb'
    - Mosaic: 'examples/Using-rio-tiler-mosaic.ipynb'
  - Migration from v1.0 to v2.0: 'v2_migration.md'
  - Development - Contributing: 'contributing.md'
  - Release Notes: 'release-notes.md'

plugins:
  - search
  - mkdocs-jupyter:
      include_source: True

# Theme
theme:
  icon:
    logo: 'material/home'
    repo: 'fontawesome/brands/github'
  name: 'material'
  language: 'en'
  palette:
    primary: 'blue'
    accent:  'light blue'
  font:
    text: 'Nunito Sans'
    code: 'Fira Code'
  custom_dir: 'docs/overrides'

# These extensions are chosen to be a superset of Pandoc's Markdown.
# This way, I can write in Pandoc's Markdown and have it be supported here.
# https://pandoc.org/MANUAL.html
markdown_extensions:
    - admonition
    - attr_list
    - codehilite:
        guess_lang: false
    - def_list
    - footnotes
    - pymdownx.arithmatex
    - pymdownx.betterem
    - pymdownx.caret:
        insert: false
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.escapeall:
        hardbreak: true
        nbsp: true
    - pymdownx.magiclink:
        hide_protocol: true
        repo_url_shortener: true
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - toc:
        permalink: true
