name: CI

# On every pull request, but only on push to main
on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
env:
  LATEST_PY_VERSION: '3.14'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          version: "0.9.*" 
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync

      - name: Run pre-commit and mypy
        if: ${{ matrix.python-version == env.LATEST_PY_VERSION }}
        run: |
          uv run pre-commit run --all-files
          uv run --with mypy --with types-attrs --with types-cachetools mypy -p rio_tiler --ignore-missing-imports

      - name: Run tests
        run: uv run pytest --cov rio_tiler --cov-report xml --cov-report term-missing -s -vv

      - name: Upload Results
        if: ${{ matrix.python-version == env.LATEST_PY_VERSION }}
        uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5
        with:
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

  benchmark:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          version: "0.9.*" 
          enable-cache: true
          python-version: ${{ env.LATEST_PY_VERSION }}

      - name: Install dependencies
        run: |
          uv sync

      - name: Run Benchmark
        run: |
          uv run --group performance pytest tests/benchmarks/benchmarks.py --benchmark-only --benchmark-columns 'min, max, mean, median' --benchmark-sort 'min' --benchmark-json output.json

      - name: Store and Compare benchmark result
        uses: benchmark-action/github-action-benchmark@a60cea5bc7b49e15c1f58f411161f99e0df48372 # v1
        with:
          name: rio-tiler Benchmarks
          tool: 'pytest'
          output-file-path: output.json
          alert-threshold: '150%'
          comment-on-alert: true
          fail-on-alert: false
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gh-pages-branch: 'gh-benchmarks'
          # Make a commit on `gh-pages` only if main
          auto-push: ${{ github.ref == 'refs/heads/main' }}
          benchmark-data-dir-path: dev/benchmarks

  benchmark-requests:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          version: "0.9.*" 
          enable-cache: true
          python-version: ${{ env.LATEST_PY_VERSION }}

      - name: Install dependencies
        run: |
          uv sync

      - name: Run Benchmark
        run: uv run --group performance pytest tests/benchmarks/requests.py -s -vv
