name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      # Only rebuild website when docs or python files have changed
      - 'README.md'
      - 'CHANGES.md'
      - 'CONTRIBUTING.md'
      - 'docs/**'
      - 'rio_tiler/**.py'
      - .github/workflows/deploy_mkdocs.yml

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.9.*" 
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --group docs

      - name: Set module version
        id: module
        run: |
          echo version=$(uv run python -c'import rio_tiler; print(rio_tiler.__version__)') >> $GITHUB_OUTPUT

      - name: Configure Git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Fetch gh-pages repository
        run: |
          git fetch origin gh-pages --depth=1

      - name: Deploy documentation (main → latest alias)
        if: github.ref_type == 'branch'
        run: uv run mike deploy latest --update-aliases --push --config-file docs/mkdocs.yml

      - name: Deploy documentation (tag → version only)
        if: github.ref_type == 'tag'
        run: uv run mike deploy ${{ steps.module.outputs.version }} --push --config-file docs/mkdocs.yml
